# Generated by Django 3.0.7 on 2020-06-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_remove_solicitud_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Persona'),
        ),
    ]
